# docker-compose.yml
version: '3.8' # You can remove this line to fix the warning

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=credit_db
      - POSTGRES_USER=credit_user
      - POSTGRES_PASSWORD=credit_password
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=credit_db
      - POSTGRES_USER=credit_user
      - POSTGRES_PASSWORD=credit_password
      - POSTGRES_HOST=db
    depends_on:
      - db

  celery_worker:
    build: ./backend
    command: celery -A credit_project worker -l info
    volumes:
      - ./backend:/app
      - ./data:/app/data
    # --- ADD THIS ENTIRE BLOCK ---
    environment:
      - POSTGRES_NAME=credit_db
      - POSTGRES_USER=credit_user
      - POSTGRES_PASSWORD=credit_password
      - POSTGRES_HOST=db
    # -----------------------------
    depends_on:
      - db
      - redis

volumes:
  postgres_data: